### ISSUE TITLE
如何处理recycleView中多个itemtype的滑动冲突？

### ISSUE THREAD

**Issue by zhangxianpeng** [BLCodes/LightRefresh#2]
我的recycleView中有多重itemType，然后其中一个itemType中有一个横向滑动的horizonlayout，然后在这个itemType滑动时没到界面顶部就可以触发下拉刷新的动作，这个问题应该如何解决呢？

**Comment by tangxianqiang** [comment]
这个给itemType无关，是事件冲突了，可以解决，我早上给你看一看

**Comment by zhangxianpeng** [comment]
好的，解决了请及时回复，谢谢

**Comment by tangxianqiang** [comment]
你可以参照我demo里面的 RecyclerView+ViewPager的做法，原理都是一样的。我自己做了横向滚动的测试，没有问题的。你也可以再看看我发布在简书上的文章https://www.jianshu.com/p/a8f3563d42cb 因为LightRefresh是在回调中实时做的冲突处理，所以你可以看看这方法的具体实现（这是下拉刷新加侧拉删除的冲突处理代码）
```
bounceLayout.setEventForwardingHelper((downX, downY, moveX, moveY) -> {
            View view =  rvAddress.findChildViewUnder(downX,downY);//获取列表中正在进行事件的item
            if (view!=null) {
                if (Math.abs(view.getScrollX()) > 0) {
                    bounceLayout.setRefreshCompleted();//这样会初始化bounceLayout
                    return false;//侧拉
                }
            }
           //判断是侧拉还是下拉刷新， x>y 侧拉，反之
            float distanceX = Math.abs(moveX - downX);
            float distanceY = Math.abs(moveY - downY);
            return !(distanceX >= distanceY);//进行判断
        });
``` 
这个回调为false则表示子view自己消费事件，也就是你的横向滚动之类的响应，而不是响应下拉刷新，注意使用的版本：com.github.BLCodes:LightRefresh:1.0.3-beta-6  其实在这个回调中可以很灵活的处理事件冲突，关键在于怎么返回true和false。如果你确实不能 解决，加我QQ：2927001935，我会帮助你解决
